"didalam komputer terdiri dari banyak bit atau binary digit bisa disebut bilangan biner"
"yaitu bilangan satu atau nol seperti transistor yg dialiri listrik"
"sekarang komputer sudah menggunakan RAM untuk membagi bit bit tsb menjadi beberapa potongan yaitu disebut VALUE / NILAI"
"VALUE / NILAI tsb memiliki peran yang disebut TIPE DATA"
"javascript 6 TIPEDATA = NUMBER, STRING, BOOLEAN, OBJECT, FUNCTION, UNDEFINED"
